[platformio]
default_envs = twatch_ultra
boards_dir = boards

[env:twatch_ultra]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = lilygo-t-watch-ultra
board_build.partitions = partitions_m33k_16MB.csv
upload_speed = 921600
monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_T_WATCH_S3_ULTRA
    -D ARDUINO_LILYGO_LORA_SX1262
    -D USING_LVGL_VER9
    -I variants/lilygo_twatch_ultra
    -D RADIOLIB_EXCLUDE_RF69
    -D RADIOLIB_EXCLUDE_SX1231
    -D RADIOLIB_EXCLUDE_RFM2X
    -D RADIOLIB_EXCLUDE_SX127X
    -D RADIOLIB_EXCLUDE_AFSK
    -D RADIOLIB_EXCLUDE_AX25
    -D RADIOLIB_EXCLUDE_HELLSCHREIBER
    -D RADIOLIB_EXCLUDE_MORSE
    -D RADIOLIB_EXCLUDE_RTTY
    -D RADIOLIB_EXCLUDE_SSTV
    -D RADIOLIB_EXCLUDE_DIRECT_RECEIVE
    -D RADIOLIB_EXCLUDE_APRS
    -D RADIOLIB_EXCLUDE_BELL

lib_deps =
    lvgl/lvgl @ 9.4.0
    jgromes/RadioLib @ ^7.4.0
    lewisxhe/XPowersLib @ ^0.3.1
    mikalhart/TinyGPSPlus @ ^1.0.3
    h2zero/NimBLE-Arduino @ 2.5.1
